Repository cartertaylor/SociAll, pull requests merged in 2021-04, with the labels that each got.

#75 Unique pages generated + bug Fixes
  website/index.html
  website/res/js/homepage.js
  website/res/js/profile.js
Labels: bug, enhancement

#82 Updating textbot to function with database
  website/textbot/text_chat.py
Labels: enhancement

#90 Adds ability for created users to login to a unique session to them
  website/passport-config.js
  website/public/formerIndex
  website/public/res/css/landingPage.css
  website/routes/home.js
  website/server.js
  website/views/index.hbs
  website/views/profile.hbs
  website/views/test.hbs
Labels: enhancement

#91 bug fixes log in
  website/passport-config.js
  website/public/checkViewsHandlebars.html
Labels: bug

#92 Contact us functionality
  website/public/flaskApps/applications.py
  website/public/otherPages/contact.html
  website/views/index.hbs
Labels: enhancement

#94 fixes some CSS bugs on the home page
  website/passport-config.js
  website/public/res/css/footer.css
  website/public/res/css/landingPage.css
  website/views/index.hbs
Labels: bug

#102 Edits Handlebars user pages for new themes
  website/public/otherPages/contact.html
  website/public/res/css/header.css
  website/public/res/css/home.css
  website/views/profile.hbs
  website/views/userpage.hbs
Labels: enhancement

#108 adds the ability for user to change their bio information on profile
  website/routes/authenticated-profile.js
  website/routes/home.js
  website/server.js
  website/views/profile.hbs
  website/views/userpage.hbs
Labels: enhancement

#125 Bot refactor
  website/public/flaskApps/applications.py
Labels: enhancement
